from enum import Enum

## Genetic Algorithm Config
POPULATION_SIZE = 2000
GENERATIONS = 100
ITERATIONS_PER_GENERATION = 5
RANDOM_MEMBERS_TO_ADD = 0
MUTATION_RATE = 70
TOP_PARENTS_SELECTED = 100
ADD_PARENTS = True
CROSSOVERS_TO_ADD = 1000

## Neural Network Config
INPUT_SIZE = 13
OUTPUT_SIZE = 3
NEURONS_HIDDEN_LAYERS = 18
NEURONS_PER_LAYER = 6

#  Game Config
BOARD_SIZE = 18
MAX_STEPS_WITHOUT_FOOD = 500 #int(BOARD_SIZE * BOARD_SIZE / 2) #5 * BOARD_SIZE * BOARD_SIZE

class Output(Enum):
    LEFT = 0
    STRAIGHT = 1
    RIGHT = 2

class BoardCell(Enum):
    EMPTY = 0
    WALL = 1
    SNAKE = 2
    FRUIT = 3

class Direction(Enum):
    NORTH = 0
    EAST = 1
    SOUTH = 2
    WEST = 3